name: Make Repository

on:
  push:
    branches:
      - master
      - debug
  schedule:
    - cron: "21 4 * * 0"

###
# lib32-gtk2
# adwaita-dark
# gtk-theme-switch2
# lib32-libindicator-gtk2
# yambar #build error
# web-ext
# emacs-lucid
# chez-scheme
# netlify 400M+
jobs:
  build_repository:
    runs-on: ubuntu-latest
    steps:
    - name: Get current time and date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M')"

    - name: Build Packages
      uses: kitech/build-aur-packages@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        packages: >
          chez-scheme
          lib32-libxpm
          fcitx
          sfwbar
          ydcv
          buku
          recutils
          deb2targz
          lib32-openssl-1.1
          multitail
          libaegis
          netlify
          vercel
          openlist-bin
          qtscrcpy-bin
          bin32-firefox-bin
          emacs-locale-zh-cn
          emacs-lucid-lite
          getmail6
          tp-battery-mode
          vdhcoapp-bin
          gtk2
          gtk-theme-switch2
          adwaita-dark
          lib32-gtk2
          hexchat
          pidgin-gtkui
          bin32-filezilla-bin

    - name: List generated Files
      run: ls -1 > ${{ github.workspace }}/files.txt
    - name: Upload Files to Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: aurci2
        name: aurci build ${{ github.run_number }} from ${{ steps.date.outputs.date }}
        body: aurci build ${{ github.run_number }} from ${{ steps.date.outputs.date }}
        files: |
          ${{ github.workspace }}/*
        draft: false
        prerelease: false
